// ============================================================
// PLAY Command Center — Influencer Profile Generator
//
// Generates 120+ realistic influencer profiles across 8 PLAY
// verticals: fashion, music, sports, gaming, outdoors, health,
// art, culture. Each profile has real-feeling bios, handles,
// and metrics seeded for deterministic CRM demos.
// ============================================================

import type {
  InfluencerRecord,
  InfluencerStage,
  DiscoverySource,
  OutreachAttempt,
  ContentDelivery,
  InfluencerFlag,
} from "@/types/crm";
import type { PlayVertical } from "@/lib/play-verticals";
import { scoreInfluencer, classifyTier } from "@/agents/scraper/engine";
import { autoTagProfile } from "@/agents/scraper/auto-tagger";

// ---- Compact profile seed — just the unique data per influencer ----

export interface ProfileSeed {
  name: string;
  handle: string;
  bio: string;
  followers: number;
  engagement: number;
  platform?: "instagram" | "tiktok" | "youtube" | "twitter";
  niche: string[];
  tags: string[];
  verticals: PlayVertical[];
  source?: DiscoverySource;
  discoveredFrom?: string;
  stage?: InfluencerStage;
  fee?: number;
  location?: string;
  flags?: string[];
  notes?: string[];
}

// ---- Helper utilities ----

function seededId(prefix: string, index: number): string {
  return `${prefix}-${String(index).padStart(4, "0")}`;
}

function platformUrl(handle: string, platform: string): string {
  switch (platform) {
    case "tiktok":
      return `https://tiktok.com/@${handle}`;
    case "youtube":
      return `https://youtube.com/@${handle}`;
    case "twitter":
      return `https://twitter.com/${handle}`;
    default:
      return `https://instagram.com/${handle}`;
  }
}

function staggeredDate(index: number, totalCount: number): string {
  // Day 1: 2026-02-25, Day 2: 2026-02-26, Day 3: 2026-02-27
  const dayOffsets = [0, 1, 2]; // relative to Feb 25
  const bucket = index / totalCount;
  let dayOffset: number;
  if (bucket < 0.4) dayOffset = dayOffsets[0]; // 40% discovered day 1
  else if (bucket < 0.75) dayOffset = dayOffsets[1]; // 35% discovered day 2
  else dayOffset = dayOffsets[2]; // 25% discovered day 3 (today)

  const hour = 8 + (index % 14); // 8am-9pm spread
  const minute = (index * 7) % 60;
  return `2026-02-${25 + dayOffset}T${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}:00Z`;
}

function buildOutreachAttempts(
  stage: InfluencerStage,
  handle: string,
  discoveredAt: string
): OutreachAttempt[] {
  const attempts: OutreachAttempt[] = [];
  const advancedStages: InfluencerStage[] = [
    "outreach_sent",
    "responded",
    "negotiating",
    "contracted",
    "onboarded",
    "active",
    "content_live",
    "completed",
  ];

  if (!advancedStages.includes(stage) && stage !== "unresponsive") {
    return attempts;
  }

  // First DM
  const sentDate = new Date(new Date(discoveredAt).getTime() + 2 * 3600000);
  attempts.push({
    id: `out-${handle}-1`,
    type: "dm_instagram",
    sentAt: sentDate.toISOString(),
    templateId: "tpl-initial-dm",
    status: stage === "unresponsive" ? "ignored" : "delivered",
    message: `Hey @${handle}! We love your content and think you'd be a perfect fit for PLAY by Palm Angels. Interested in a collab?`,
    automated: true,
  });

  if (stage === "unresponsive") {
    // Add a follow-up that was also ignored
    const followUp = new Date(sentDate.getTime() + 48 * 3600000);
    attempts.push({
      id: `out-${handle}-2`,
      type: "dm_instagram",
      sentAt: followUp.toISOString(),
      templateId: "tpl-follow-up-1",
      status: "ignored",
      message: `Just following up @${handle} -- would love to chat about a PLAY collab whenever you have a sec!`,
      automated: true,
    });
    return attempts;
  }

  if (stage === "outreach_sent") return attempts;

  // They replied
  const respondedStages: InfluencerStage[] = [
    "responded",
    "negotiating",
    "contracted",
    "onboarded",
    "active",
    "content_live",
    "completed",
  ];
  if (respondedStages.includes(stage)) {
    attempts[0].status = "replied";
    attempts[0].response = "Hey! Sounds interesting, tell me more about the campaign?";
    attempts[0].respondedAt = new Date(sentDate.getTime() + 8 * 3600000).toISOString();
  }

  // Negotiation email for contracted+
  const contractedStages: InfluencerStage[] = [
    "contracted",
    "onboarded",
    "active",
    "content_live",
    "completed",
  ];
  if (contractedStages.includes(stage)) {
    const negoDate = new Date(sentDate.getTime() + 24 * 3600000);
    attempts.push({
      id: `out-${handle}-2`,
      type: "email",
      sentAt: negoDate.toISOString(),
      templateId: "tpl-negotiation",
      status: "replied",
      message: `Hi ${handle.replace(/[._]/g, " ")}, here are the campaign details and deliverables for PLAY x you. Let us know your rate and availability.`,
      response: "Looks great, I'm in. Sending my rate card now.",
      respondedAt: new Date(negoDate.getTime() + 12 * 3600000).toISOString(),
      automated: false,
    });
  }

  return attempts;
}

function buildContentPieces(stage: InfluencerStage, handle: string): ContentDelivery[] {
  const liveStages: InfluencerStage[] = ["content_live", "completed", "active"];
  if (!liveStages.includes(stage)) return [];

  const pieces: ContentDelivery[] = [
    {
      id: `content-${handle}-1`,
      type: "reel",
      platform: "instagram",
      postUrl: `https://instagram.com/reel/${handle}_play_collab`,
      publishedDate: "2026-02-26T14:00:00Z",
      status: "published",
      impressions: Math.floor(Math.random() * 200000) + 50000,
      engagement: Math.floor(Math.random() * 15000) + 3000,
      clicks: Math.floor(Math.random() * 2000) + 200,
      conversions: Math.floor(Math.random() * 80) + 10,
    },
  ];

  if (stage === "completed") {
    pieces.push({
      id: `content-${handle}-2`,
      type: "story",
      platform: "instagram",
      publishedDate: "2026-02-27T10:00:00Z",
      status: "published",
      impressions: Math.floor(Math.random() * 80000) + 20000,
      engagement: Math.floor(Math.random() * 5000) + 1000,
      clicks: Math.floor(Math.random() * 800) + 100,
      conversions: Math.floor(Math.random() * 30) + 5,
    });
  }

  return pieces;
}

// ---- Core factory function ----

export function makeInfluencer(seed: ProfileSeed, index: number): InfluencerRecord {
  const platform = seed.platform || "instagram";
  const stage = seed.stage || "discovered";
  const source = seed.source || "scraper_comment";
  const totalProfiles = 120;
  const discoveredAt = staggeredDate(index, totalProfiles);

  const score = scoreInfluencer({
    followers: seed.followers,
    engagementRate: seed.engagement,
    bio: seed.bio,
    niche: seed.niche,
    platform,
  });

  const tier = classifyTier(seed.followers);

  // Use autoTagProfile to enhance tags if the seed has sparse tags
  const enrichedTags = seed.tags.length < 3
    ? autoTagProfile({ bio: seed.bio, niche: seed.niche, handle: seed.handle }).tags
    : seed.tags;

  const avgLikes = Math.round(seed.followers * (seed.engagement / 100) * 0.85);
  const avgComments = Math.round(avgLikes * 0.06);
  const followingCount = Math.round(seed.followers * (0.05 + Math.random() * 0.15));

  const outreachAttempts = buildOutreachAttempts(stage, seed.handle, discoveredAt);
  const contentPieces = buildContentPieces(stage, seed.handle);

  const totalReach = contentPieces.reduce((sum, c) => sum + c.impressions, 0);
  const totalEngagement = contentPieces.reduce((sum, c) => sum + c.engagement, 0);

  // Determine fee for contracted+ stages
  const contractedPlus: InfluencerStage[] = [
    "contracted",
    "onboarded",
    "active",
    "content_live",
    "completed",
  ];
  let fee = seed.fee;
  if (!fee && contractedPlus.includes(stage)) {
    if (tier === "mega") fee = 8000 + Math.round(Math.random() * 12000);
    else if (tier === "macro") fee = 3000 + Math.round(Math.random() * 5000);
    else if (tier === "mid") fee = 1000 + Math.round(Math.random() * 2000);
    else fee = 300 + Math.round(Math.random() * 700);
  }

  const lastContactedAt = outreachAttempts.length > 0
    ? outreachAttempts[outreachAttempts.length - 1].sentAt
    : undefined;

  const contractStatus = contractedPlus.includes(stage) ? "signed" as const : undefined;

  const flags: InfluencerFlag[] = (seed.flags || []) as InfluencerFlag[];

  return {
    id: seededId("inf", index),
    name: seed.name,
    handle: seed.handle,
    platform,
    profileUrl: platformUrl(seed.handle, platform),
    bio: seed.bio,
    location: seed.location,
    followers: seed.followers,
    followingCount,
    avgLikes,
    avgComments,
    engagementRate: seed.engagement,
    tier,
    niche: seed.niche,
    brandAffinity: Math.min(score + Math.round(Math.random() * 10), 100),
    stage,
    source,
    discoveredAt,
    discoveredFrom: seed.discoveredFrom,
    score,
    outreachAttempts,
    lastContactedAt,
    fee,
    contractStatus,
    contentPieces,
    totalReach,
    totalEngagement,
    roi: totalReach > 0 && fee ? Math.round((totalEngagement / fee) * 100) / 100 : undefined,
    tags: enrichedTags,
    notes: seed.notes || [],
    flags,
    deliverables: contractedPlus.includes(stage)
      ? ["1x Instagram Reel", "2x Stories", "1x Feed Post"]
      : undefined,
  };
}

// ============================================================
//  FASHION PROFILES (30)
// ============================================================

export const FASHION_PROFILES: ProfileSeed[] = [
  // --- Mega (3) ---
  {
    name: "Marcus Chen",
    handle: "marcstyle",
    bio: "Streetwear curator | NYC fits daily | Palm Angels x Off-White | Collabs: marc@stylemgmt.co",
    followers: 1320000,
    engagement: 3.8,
    niche: ["fashion", "streetwear", "sneakers"],
    tags: ["streetwear", "sneakers", "menswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "contracted",
    fee: 12000,
    location: "New York, NY",
    flags: ["vip", "brand_safe"],
  },
  {
    name: "Isabella Moretti",
    handle: "bellamoretti",
    bio: "Fashion editor turned creator | Vogue, Elle | Styling the future of luxury streetwear | Mgmt: @nextmodels",
    followers: 2100000,
    engagement: 2.9,
    niche: ["fashion", "luxury", "editorial"],
    tags: ["luxury", "styling", "haute-couture"],
    verticals: ["fashion"],
    source: "agency_submit",
    discoveredFrom: "@playbypalmangels",
    stage: "negotiating",
    location: "Milan, Italy",
    flags: ["vip"],
  },
  {
    name: "Jaylen Brooks",
    handle: "jaylenbrooks",
    bio: "Model | Actor | Nike x Balenciaga x Palm Angels | Represented by IMG | LA based",
    followers: 1850000,
    engagement: 3.2,
    niche: ["fashion", "model", "lifestyle"],
    tags: ["menswear", "luxury", "streetwear"],
    verticals: ["fashion"],
    source: "manual_add",
    discoveredFrom: "@playbypalmangels",
    stage: "active",
    fee: 15000,
    location: "Los Angeles, CA",
    flags: ["vip", "brand_safe"],
  },
  // --- Macro (6) ---
  {
    name: "Sofia Reyes",
    handle: "sofiastreetwear",
    bio: "Streetwear x feminine energy | Stussy, Aries, Palm Angels | DM for styling inquiries",
    followers: 480000,
    engagement: 4.6,
    niche: ["fashion", "streetwear", "womenswear"],
    tags: ["streetwear", "womenswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Miami, FL",
  },
  {
    name: "Derek Tanaka",
    handle: "derek.drip",
    bio: "Sneaker reviewer | 500+ pairs | GOAT verified seller | Collabs with Nike, New Balance, Asics",
    followers: 310000,
    engagement: 5.1,
    niche: ["fashion", "sneakers", "streetwear"],
    tags: ["sneakers", "streetwear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "responded",
    location: "Tokyo, Japan",
  },
  {
    name: "Amara Okonkwo",
    handle: "amaralooks",
    bio: "London stylist | Dressing celebs & building brands | Balenciaga, Prada, PLAY | Book me: amara@outlook.com",
    followers: 220000,
    engagement: 4.9,
    niche: ["fashion", "styling", "luxury"],
    tags: ["styling", "luxury", "womenswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@emmachamberlain",
    stage: "outreach_sent",
    location: "London, UK",
  },
  {
    name: "Kevin Park",
    handle: "kevinparkstyle",
    bio: "Fashion photographer | Shot for Hypebeast, GQ, Complex | Available worldwide",
    followers: 175000,
    engagement: 3.8,
    niche: ["fashion", "photography", "editorial"],
    tags: ["streetwear", "designer"],
    verticals: ["fashion", "art"],
    source: "scraper_hashtag",
    discoveredFrom: "#palmangels",
    stage: "qualified",
    location: "Seoul, South Korea",
  },
  {
    name: "Natasha Volkov",
    handle: "tasha.luxe",
    bio: "Luxury fashion | Travel | Palm Angels to Chanel | Life in Monaco & NYC | PR: natasha@luxepr.co",
    followers: 620000,
    engagement: 3.4,
    niche: ["fashion", "luxury", "travel"],
    tags: ["luxury", "accessories", "designer"],
    verticals: ["fashion", "culture"],
    source: "agency_submit",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Monaco",
  },
  {
    name: "Ricky Santos",
    handle: "rickysantos.fit",
    bio: "Daily fit pics | Archive fashion nerd | Collecting Raf, Helmut Lang, Palm Angels since 2019",
    followers: 145000,
    engagement: 6.1,
    niche: ["fashion", "streetwear", "vintage"],
    tags: ["vintage", "streetwear", "menswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@wisdm",
    stage: "discovered",
    location: "Chicago, IL",
  },
  // --- Mid (12) ---
  {
    name: "Jade Thompson",
    handle: "jadethreads",
    bio: "Thrift queen | Sustainable fashion advocate | Making vintage look new | She/her",
    followers: 67000,
    engagement: 7.2,
    niche: ["fashion", "vintage", "sustainable"],
    tags: ["vintage", "sustainable-fashion", "womenswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Portland, OR",
  },
  {
    name: "Brandon Lee",
    handle: "blee.fits",
    bio: "Menswear daily | Corporate to streetwear | Stussy x Carhartt WIP x Palm Angels enthusiast",
    followers: 54000,
    engagement: 5.8,
    niche: ["fashion", "menswear", "streetwear"],
    tags: ["menswear", "streetwear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "San Francisco, CA",
  },
  {
    name: "Mia Rodriguez",
    handle: "mia.rodstyle",
    bio: "Fashion design student at Parsons | Sketching & styling | Future creative director | NYC dreamer",
    followers: 38000,
    engagement: 8.4,
    niche: ["fashion", "design", "styling"],
    tags: ["designer", "styling"],
    verticals: ["fashion"],
    source: "scraper_hashtag",
    discoveredFrom: "#streetwear",
    stage: "researching",
    location: "New York, NY",
  },
  {
    name: "Tariq Hassan",
    handle: "tariqstreetwear",
    bio: "Dubai streetwear scene | Nike SB, Palace, PLAY | Sneaker collector 300+ | Hype or nothing",
    followers: 82000,
    engagement: 6.0,
    niche: ["fashion", "streetwear", "sneakers"],
    tags: ["streetwear", "sneakers"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Dubai, UAE",
  },
  {
    name: "Lena Muller",
    handle: "lenawears",
    bio: "Berlin-based stylist | Gender-fluid fashion | Dressing for the future, not the moment",
    followers: 45000,
    engagement: 7.8,
    niche: ["fashion", "styling", "gender-fluid"],
    tags: ["styling", "womenswear", "designer"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "qualified",
    location: "Berlin, Germany",
  },
  {
    name: "Chris Nakamura",
    handle: "chrisnakfashion",
    bio: "Techwear x streetwear hybrid | Acronym, Stone Island, Palm Angels | Fit videos weekly",
    followers: 91000,
    engagement: 5.3,
    niche: ["fashion", "techwear", "streetwear"],
    tags: ["streetwear", "menswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@wisdm",
    stage: "outreach_sent",
    location: "Vancouver, Canada",
  },
  {
    name: "Zara Phillips",
    handle: "zaraphillipsstyle",
    bio: "Plus-size fashion creator | Redefining streetwear for every body | Brand collabs open",
    followers: 72000,
    engagement: 6.8,
    niche: ["fashion", "streetwear", "body-positive"],
    tags: ["streetwear", "womenswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "#fitcheck",
    stage: "responded",
    location: "Atlanta, GA",
  },
  {
    name: "Omar Farah",
    handle: "omarfarahstyle",
    bio: "East African drip | Mixing culture & fashion | Nairobi to NYC pipeline | Fear of God, PA",
    followers: 59000,
    engagement: 5.5,
    niche: ["fashion", "culture", "streetwear"],
    tags: ["streetwear", "menswear"],
    verticals: ["fashion", "culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "discovered",
    location: "Nairobi, Kenya",
  },
  {
    name: "Emma Liu",
    handle: "emmaliu.ootd",
    bio: "OOTD every damn day | Zara to Celine | Shanghai girl in LA | DM for PR",
    followers: 43000,
    engagement: 7.1,
    niche: ["fashion", "ootd", "luxury"],
    tags: ["luxury", "womenswear", "accessories"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@emmachamberlain",
    stage: "outreach_sent",
    location: "Los Angeles, CA",
  },
  {
    name: "Andre Williams",
    handle: "dre.grails",
    bio: "Grail hunter | Supreme, Bape, Palm Angels archive | If it's rare I probably have it",
    followers: 36000,
    engagement: 8.9,
    niche: ["fashion", "streetwear", "vintage"],
    tags: ["streetwear", "vintage"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "researching",
    location: "Philadelphia, PA",
  },
  {
    name: "Nina Petrova",
    handle: "nina.petr",
    bio: "Fashion illustrator | Drawing the runway | Commissioned by Dior, Valentino, Palm Angels",
    followers: 28000,
    engagement: 9.2,
    niche: ["fashion", "illustration", "art"],
    tags: ["designer", "luxury"],
    verticals: ["fashion", "art"],
    source: "scraper_hashtag",
    discoveredFrom: "#palmangels",
    stage: "outreach_sent",
    location: "Moscow, Russia",
  },
  {
    name: "Rio Jackson",
    handle: "rio.layered",
    bio: "Layering master | NYC winter fits | Carhartt WIP, Stussy, Palm Angels | Every outfit tells a story",
    followers: 47000,
    engagement: 6.3,
    niche: ["fashion", "streetwear", "layering"],
    tags: ["streetwear", "menswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@wisdm",
    stage: "outreach_sent",
    location: "New York, NY",
  },
  // --- Micro (9) ---
  {
    name: "Tyler Grant",
    handle: "ty.streetlook",
    bio: "College fits on a budget | Making $50 look like $500 | Fashion for the people",
    followers: 18500,
    engagement: 9.8,
    niche: ["fashion", "streetwear", "budget"],
    tags: ["streetwear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "discovered",
    location: "Austin, TX",
  },
  {
    name: "Priya Sharma",
    handle: "priya.fits",
    bio: "South Asian fashion fusion | Traditional meets streetwear | Palm Angels stan account",
    followers: 12300,
    engagement: 11.2,
    niche: ["fashion", "culture", "fusion"],
    tags: ["streetwear", "womenswear"],
    verticals: ["fashion", "culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Mumbai, India",
  },
  {
    name: "Jake Morrison",
    handle: "jakemostyle",
    bio: "Denim head | Raw selvedge enthusiast | Levi's vintage, Iron Heart, PA denim",
    followers: 8700,
    engagement: 10.5,
    niche: ["fashion", "denim", "vintage"],
    tags: ["denim", "vintage", "menswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "discovered",
    location: "Nashville, TN",
  },
  {
    name: "Luna Martinez",
    handle: "lunastylefile",
    bio: "Accessories queen | Jewelry, bags, shades | Every detail matters | LA stylist assistant",
    followers: 15200,
    engagement: 8.7,
    niche: ["fashion", "accessories", "styling"],
    tags: ["accessories", "styling", "womenswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@emmachamberlain",
    stage: "outreach_sent",
    location: "Los Angeles, CA",
  },
  {
    name: "Darnell Jackson",
    handle: "darnellj.drip",
    bio: "ATL drip | Trap fashion pioneer | If the fit ain't hitting, I ain't posting",
    followers: 22000,
    engagement: 7.3,
    niche: ["fashion", "streetwear", "hip-hop"],
    tags: ["streetwear", "menswear"],
    verticals: ["fashion", "music"],
    source: "scraper_comment",
    discoveredFrom: "@travisscott",
    stage: "qualified",
    location: "Atlanta, GA",
  },
  {
    name: "Aiko Watanabe",
    handle: "aiko.harajuku",
    bio: "Harajuku street style | Mixing Comme des Garcons with Palm Angels | Tokyo fashion diary",
    followers: 19800,
    engagement: 9.1,
    niche: ["fashion", "streetwear", "japanese-fashion"],
    tags: ["streetwear", "designer"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "outreach_sent",
    location: "Tokyo, Japan",
  },
  {
    name: "Sam Rivera",
    handle: "samriv.kicks",
    bio: "Sneaker photographer | Nike Dunk archive | Shooting heat for brands | Bookings open",
    followers: 14000,
    engagement: 10.0,
    niche: ["fashion", "sneakers", "photography"],
    tags: ["sneakers", "streetwear"],
    verticals: ["fashion", "art"],
    source: "scraper_hashtag",
    discoveredFrom: "#streetwear",
    stage: "discovered",
    location: "Houston, TX",
  },
  {
    name: "Casey Brennan",
    handle: "casey.b.style",
    bio: "Non-binary fashion creative | Breaking the binary one fit at a time | They/them",
    followers: 9500,
    engagement: 12.1,
    niche: ["fashion", "gender-fluid", "creative"],
    tags: ["styling", "streetwear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Brooklyn, NY",
  },
  {
    name: "Victor Almeida",
    handle: "vic.almeidafits",
    bio: "Brazilian streetwear from Sao Paulo | Mixing local brands with Palm Angels, Off-White | Hmu for collabs",
    followers: 11000,
    engagement: 8.5,
    niche: ["fashion", "streetwear", "latin"],
    tags: ["streetwear", "menswear"],
    verticals: ["fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "discovered",
    location: "Sao Paulo, Brazil",
  },
];

// ============================================================
//  MUSIC PROFILES (18)
// ============================================================

export const MUSIC_PROFILES: ProfileSeed[] = [
  // --- Mega (2) ---
  {
    name: "Kai Nomura",
    handle: "prodbykai",
    bio: "Producer | 2B+ streams | Credits: Travis Scott, Don Toliver, Metro Boomin | Studio rat | Palm Angels in the booth",
    followers: 1750000,
    engagement: 3.1,
    niche: ["music", "production", "hip-hop"],
    tags: ["producer", "hip-hop"],
    verticals: ["music"],
    source: "manual_add",
    discoveredFrom: "@travisscott",
    stage: "negotiating",
    location: "Los Angeles, CA",
    flags: ["vip"],
  },
  {
    name: "DJ Nova",
    handle: "djnova_official",
    bio: "International DJ | Ibiza resident | 800K monthly Spotify listeners | Fashion meets the decks | Bookings: nova@beats.co",
    followers: 1200000,
    engagement: 2.8,
    niche: ["music", "dj", "electronic"],
    tags: ["dj", "electronic"],
    verticals: ["music", "culture"],
    source: "agency_submit",
    discoveredFrom: "@playbypalmangels",
    stage: "contracted",
    fee: 10000,
    location: "Ibiza, Spain",
    flags: ["vip", "brand_safe"],
  },
  // --- Macro (4) ---
  {
    name: "Melody Osei",
    handle: "melodymadeit",
    bio: "Singer-songwriter | R&B soul | 200M+ streams | New album dropping soon | Fashion is my second love",
    followers: 480000,
    engagement: 4.2,
    niche: ["music", "r&b", "fashion"],
    tags: ["singer", "r&b", "streetwear"],
    verticals: ["music", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "London, UK",
  },
  {
    name: "Benji Torres",
    handle: "trapbenji",
    bio: "Trap producer & rapper | Miami bass meets ATL trap | 50M streams | PLAY is the vibe",
    followers: 320000,
    engagement: 5.0,
    niche: ["music", "rap", "production"],
    tags: ["rapper", "hip-hop", "producer"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "@travisscott",
    stage: "outreach_sent",
    location: "Miami, FL",
  },
  {
    name: "Zoe Laurent",
    handle: "zoelaurent.wav",
    bio: "Electronic producer | Classically trained, digitally unhinged | Releases on Anjunadeep, Defected",
    followers: 195000,
    engagement: 4.7,
    niche: ["music", "electronic", "production"],
    tags: ["electronic", "producer"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "responded",
    location: "Paris, France",
  },
  {
    name: "Marcus Vega",
    handle: "marcusvega.music",
    bio: "Latin hip-hop artist | Reggaeton x trap | 100M views on YT | Fashion collabs always open",
    followers: 410000,
    engagement: 3.9,
    niche: ["music", "reggaeton", "hip-hop"],
    tags: ["rapper", "hip-hop"],
    verticals: ["music", "culture"],
    source: "referral",
    discoveredFrom: "@playbypalmangels",
    stage: "qualified",
    location: "San Juan, PR",
  },
  // --- Mid (6) ---
  {
    name: "Ava Chen",
    handle: "avachenmusic",
    bio: "Indie R&B | Piano + vocals | 20M streams | NYC live shows | Fashion girlie who makes music",
    followers: 78000,
    engagement: 6.5,
    niche: ["music", "r&b", "indie"],
    tags: ["singer", "r&b", "songwriter"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "New York, NY",
  },
  {
    name: "Dex Morgan",
    handle: "dex.onthebeat",
    bio: "Beat maker | YouTube tutorials | 500+ beats sold | Working with independent rappers worldwide",
    followers: 52000,
    engagement: 7.1,
    niche: ["music", "production", "hip-hop"],
    tags: ["producer", "hip-hop"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "discovered",
    location: "Detroit, MI",
  },
  {
    name: "Jasmine Wells",
    handle: "jaswells.live",
    bio: "Live performer | Festival circuit | Opening for headliners | Music + fashion content | She/her",
    followers: 64000,
    engagement: 5.9,
    niche: ["music", "live", "festival"],
    tags: ["concert", "singer"],
    verticals: ["music", "culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Austin, TX",
  },
  {
    name: "Yuki Tanaka",
    handle: "yukibeats_",
    bio: "Lo-fi producer | Chillhop regular | 10M streams | Making beats in Palm Angels sweats",
    followers: 41000,
    engagement: 8.2,
    niche: ["music", "lo-fi", "electronic"],
    tags: ["producer", "electronic"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Osaka, Japan",
  },
  {
    name: "Rashid Ali",
    handle: "rashid.rap",
    bio: "Underground rapper | Spoken word artist | Fashion as expression | Philadelphia bars",
    followers: 35000,
    engagement: 7.8,
    niche: ["music", "rap", "spoken-word"],
    tags: ["rapper", "hip-hop"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "researching",
    location: "Philadelphia, PA",
  },
  {
    name: "Simone Baker",
    handle: "simonebaker.dj",
    bio: "DJ & vinyl collector | House, techno, disco | Playing every rooftop in Brooklyn this summer",
    followers: 29000,
    engagement: 6.8,
    niche: ["music", "dj", "vinyl"],
    tags: ["dj", "vinyl"],
    verticals: ["music", "culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "qualified",
    location: "Brooklyn, NY",
  },
  // --- Micro (6) ---
  {
    name: "Leo Park",
    handle: "leopark.studio",
    bio: "Bedroom producer | Synth enthusiast | Dropping my debut EP soon | Music is therapy",
    followers: 14500,
    engagement: 10.3,
    niche: ["music", "electronic", "indie"],
    tags: ["producer", "electronic"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "discovered",
    location: "Seattle, WA",
  },
  {
    name: "Nadia Flores",
    handle: "nadiaflores.vox",
    bio: "Vocalist | Session singer for hire | Bilingual (EN/ES) | Music + fashion content creator",
    followers: 11200,
    engagement: 9.5,
    niche: ["music", "vocals", "latin"],
    tags: ["singer", "songwriter"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Mexico City, MX",
  },
  {
    name: "Trey Robinson",
    handle: "trey.drumlife",
    bio: "Drummer | Session musician | Playing behind major artists | Fashion forward musician life",
    followers: 8900,
    engagement: 11.0,
    niche: ["music", "drums", "live"],
    tags: ["concert", "hip-hop"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "discovered",
    location: "Nashville, TN",
  },
  {
    name: "Mira Johansson",
    handle: "mirabeats.se",
    bio: "Swedish producer | Pop meets electronic | Writing for labels | Stockholm nights",
    followers: 7600,
    engagement: 12.4,
    niche: ["music", "pop", "electronic"],
    tags: ["producer", "pop"],
    verticals: ["music"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Stockholm, Sweden",
  },
  {
    name: "Dante Cruz",
    handle: "dantecruz.mc",
    bio: "MC & freestyler | Battle rap to brand deals | Fashion is armor | DMV area",
    followers: 19500,
    engagement: 8.0,
    niche: ["music", "rap", "freestyle"],
    tags: ["rapper", "hip-hop"],
    verticals: ["music", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@travisscott",
    stage: "outreach_sent",
    location: "Washington, DC",
  },
  {
    name: "Elise Moreau",
    handle: "elisemoreau.keys",
    bio: "Pianist & composer | Scoring short films | Classical meets trap | Paris conservatory grad",
    followers: 6200,
    engagement: 13.5,
    niche: ["music", "classical", "composition"],
    tags: ["songwriter", "music-video"],
    verticals: ["music", "art"],
    source: "scraper_hashtag",
    discoveredFrom: "#palmangels",
    stage: "discovered",
    location: "Paris, France",
  },
];

// ============================================================
//  SPORTS PROFILES (16)
// ============================================================

export const SPORTS_PROFILES: ProfileSeed[] = [
  // --- Mega (2) ---
  {
    name: "Jaylen Carter",
    handle: "hoopslife_jay",
    bio: "NBA G-League | Basketball is life | Off-court style: Palm Angels, Nike, Dior | God first",
    followers: 1450000,
    engagement: 3.5,
    niche: ["sports", "basketball", "fashion"],
    tags: ["basketball", "menswear", "streetwear"],
    verticals: ["sports", "fashion"],
    source: "manual_add",
    discoveredFrom: "@playbypalmangels",
    stage: "onboarded",
    fee: 18000,
    location: "Houston, TX",
    flags: ["vip", "brand_safe"],
  },
  {
    name: "Mike Alvarez",
    handle: "sk8rboi.mike",
    bio: "Pro skater | X Games medalist | Element, Nike SB, Palm Angels | Filming parts & living the dream",
    followers: 1100000,
    engagement: 4.1,
    niche: ["sports", "skateboarding", "streetwear"],
    tags: ["skateboarding", "streetwear"],
    verticals: ["sports", "fashion"],
    source: "agency_submit",
    discoveredFrom: "@playbypalmangels",
    stage: "content_live",
    fee: 14000,
    location: "Venice Beach, CA",
    flags: ["vip"],
  },
  // --- Macro (3) ---
  {
    name: "Kai Lani",
    handle: "surfkai",
    bio: "Pro surfer | WSL competitor | Ocean life | Sustainable fashion advocate | Billabong, Palm Angels",
    followers: 380000,
    engagement: 4.8,
    niche: ["sports", "surfing", "lifestyle"],
    tags: ["surfing", "streetwear"],
    verticals: ["sports", "outdoors"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "North Shore, HI",
  },
  {
    name: "Marcus Diaz",
    handle: "mma.marcus",
    bio: "MMA fighter | UFC ranked | Training daily | Fashion game strong outside the octagon | Team PLAY",
    followers: 290000,
    engagement: 5.3,
    niche: ["sports", "mma", "fitness"],
    tags: ["mma", "boxing"],
    verticals: ["sports"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "responded",
    location: "Las Vegas, NV",
  },
  {
    name: "Elena Rossi",
    handle: "elenarossi.run",
    bio: "Olympic marathoner | Nike athlete | Athleisure queen | Training runs in Palm Angels | Rome to NYC",
    followers: 210000,
    engagement: 4.0,
    niche: ["sports", "running", "athleisure"],
    tags: ["running", "menswear"],
    verticals: ["sports", "health"],
    source: "agency_submit",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Rome, Italy",
  },
  // --- Mid (6) ---
  {
    name: "Jordan Blake",
    handle: "jordanblake.hoop",
    bio: "College basketball | D1 athlete | Pre-game fits matter | Next up | Hoopin & stylin",
    followers: 72000,
    engagement: 6.5,
    niche: ["sports", "basketball", "fashion"],
    tags: ["basketball", "streetwear"],
    verticals: ["sports", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Durham, NC",
  },
  {
    name: "Chloe Nakamura",
    handle: "chloe.sk8s",
    bio: "Skater girl | Street skating Tokyo | Film my sessions | Fashion x skating content",
    followers: 58000,
    engagement: 7.2,
    niche: ["sports", "skateboarding", "fashion"],
    tags: ["skateboarding", "streetwear"],
    verticals: ["sports", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "qualified",
    location: "Tokyo, Japan",
  },
  {
    name: "Diego Fernandez",
    handle: "diego.futbol",
    bio: "Semi-pro footballer | Training content | La Liga dreams | Off-pitch style is everything",
    followers: 45000,
    engagement: 5.9,
    niche: ["sports", "soccer", "lifestyle"],
    tags: ["soccer", "menswear"],
    verticals: ["sports"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Barcelona, Spain",
  },
  {
    name: "Nia Washington",
    handle: "nia.boxfit",
    bio: "Boxing trainer | Celebrity clients | Fitness fashion content | Strong is the new pretty",
    followers: 67000,
    engagement: 6.1,
    niche: ["sports", "boxing", "fitness"],
    tags: ["boxing", "menswear"],
    verticals: ["sports", "health"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "discovered",
    location: "New York, NY",
  },
  {
    name: "Ryan Kowalski",
    handle: "ryankowalski.snow",
    bio: "Pro snowboarder | Burton rider | Winter sport meets street style | Colorado based",
    followers: 39000,
    engagement: 7.8,
    niche: ["sports", "snowboarding", "outdoor"],
    tags: ["snowboarding", "streetwear"],
    verticals: ["sports", "outdoors"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "outreach_sent",
    location: "Aspen, CO",
  },
  {
    name: "Aisha Keita",
    handle: "aisha.courts",
    bio: "Tennis player | WTA futures | Off-court fashion is my main character energy | Adidas, PA",
    followers: 51000,
    engagement: 5.6,
    niche: ["sports", "tennis", "fashion"],
    tags: ["tennis", "womenswear"],
    verticals: ["sports", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Paris, France",
  },
  // --- Micro (5) ---
  {
    name: "Tommy Reeves",
    handle: "tommy.bmxlife",
    bio: "BMX rider | Street riding & park sessions | Filming tricks daily | Fashion between flips",
    followers: 22000,
    engagement: 8.4,
    niche: ["sports", "bmx", "action"],
    tags: ["bmx", "streetwear"],
    verticals: ["sports"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "outreach_sent",
    location: "San Diego, CA",
  },
  {
    name: "Layla Ahmed",
    handle: "layla.climbs",
    bio: "Rock climber | Bouldering V10 | Outdoor athlete | Mixing technical gear with streetwear vibes",
    followers: 16500,
    engagement: 9.3,
    niche: ["sports", "climbing", "outdoor"],
    tags: ["climbing", "streetwear"],
    verticals: ["sports", "outdoors"],
    source: "scraper_hashtag",
    discoveredFrom: "#palmangels",
    stage: "discovered",
    location: "Boulder, CO",
  },
  {
    name: "Xavier Price",
    handle: "xav.tracklife",
    bio: "Track & field sprinter | 10.4s 100m | Chasing Olympic dreams | Pre-race drip is mandatory",
    followers: 13200,
    engagement: 10.1,
    niche: ["sports", "track", "fitness"],
    tags: ["running", "menswear"],
    verticals: ["sports"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Eugene, OR",
  },
  {
    name: "Malia Kealoha",
    handle: "malia.waves",
    bio: "Surfer girl | Maui raised | Catching waves & catching looks | Ocean is my runway",
    followers: 19800,
    engagement: 8.7,
    niche: ["sports", "surfing", "lifestyle"],
    tags: ["surfing", "womenswear"],
    verticals: ["sports", "outdoors"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "qualified",
    location: "Maui, HI",
  },
  {
    name: "Renzo Bianchi",
    handle: "renzo.jiujitsu",
    bio: "BJJ black belt | Competitor & coach | Athleisure 24/7 | Training in Palm Angels sweats",
    followers: 9800,
    engagement: 11.2,
    niche: ["sports", "mma", "fitness"],
    tags: ["mma", "menswear"],
    verticals: ["sports", "health"],
    source: "scraper_comment",
    discoveredFrom: "#fitcheck",
    stage: "discovered",
    location: "Rio de Janeiro, Brazil",
  },
];

// ============================================================
//  GAMING PROFILES (12)
// ============================================================

export const GAMING_PROFILES: ProfileSeed[] = [
  // --- Mega (1) ---
  {
    name: "Nova Chen",
    handle: "neonplays",
    bio: "Twitch partner | 2M subs | Valorant & variety | Fashion in gaming is the future | PLAY x Gaming",
    followers: 2400000,
    engagement: 2.6,
    platform: "youtube",
    niche: ["gaming", "streaming", "fashion"],
    tags: ["streaming", "esports", "streetwear"],
    verticals: ["gaming", "fashion"],
    source: "manual_add",
    discoveredFrom: "#gamingfashion",
    stage: "contracted",
    fee: 20000,
    location: "Toronto, Canada",
    flags: ["vip", "brand_safe"],
  },
  // --- Macro (3) ---
  {
    name: "Tyler Kim",
    handle: "clutchgaming_",
    bio: "Esports pro | FaZe alumni | Content creator | Merging gaming & street fashion | 500K on Twitch",
    followers: 680000,
    engagement: 4.2,
    niche: ["gaming", "esports", "fashion"],
    tags: ["esports", "competitive", "streetwear"],
    verticals: ["gaming", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "#gamingfashion",
    stage: "outreach_sent",
    location: "Los Angeles, CA",
  },
  {
    name: "Aria Patel",
    handle: "pixeldrip",
    bio: "Gaming + fashion content | Styling my character & myself | 200K on TikTok | Cosplay x streetwear",
    followers: 350000,
    engagement: 5.1,
    platform: "tiktok",
    niche: ["gaming", "fashion", "cosplay"],
    tags: ["content-creator", "streaming", "streetwear"],
    verticals: ["gaming", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "responded",
    location: "San Francisco, CA",
  },
  {
    name: "Jake 'Phantom' O'Brien",
    handle: "phantomjake",
    bio: "Variety streamer | Fortnite, Apex, COD | Full-time content creator | Fashion hauls between streams",
    followers: 290000,
    engagement: 4.8,
    platform: "youtube",
    niche: ["gaming", "streaming", "lifestyle"],
    tags: ["streaming", "content-creator"],
    verticals: ["gaming"],
    source: "scraper_comment",
    discoveredFrom: "#gamingfashion",
    stage: "outreach_sent",
    location: "Dublin, Ireland",
  },
  // --- Mid (4) ---
  {
    name: "Mei Lin",
    handle: "meilin.plays",
    bio: "Competitive Valorant | Fashion between matches | Building the gaming x fashion bridge | GG",
    followers: 82000,
    engagement: 6.3,
    niche: ["gaming", "esports", "fashion"],
    tags: ["esports", "competitive", "streetwear"],
    verticals: ["gaming", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "#gamingfashion",
    stage: "outreach_sent",
    location: "Shanghai, China",
  },
  {
    name: "Chris Duval",
    handle: "chrisduval.gg",
    bio: "Retro gaming collector | Streaming SNES to PS5 | Vintage tees & vintage games | Nostalgia king",
    followers: 56000,
    engagement: 7.4,
    niche: ["gaming", "retro", "lifestyle"],
    tags: ["retro", "content-creator"],
    verticals: ["gaming"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "discovered",
    location: "Montreal, Canada",
  },
  {
    name: "Destiny Owens",
    handle: "destinyowens.ttv",
    bio: "Twitch streamer | Just chatting + Minecraft | Fashion reviews on stream | Community first",
    followers: 44000,
    engagement: 8.1,
    niche: ["gaming", "streaming", "fashion"],
    tags: ["streaming", "casual"],
    verticals: ["gaming", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "#gamingfashion",
    stage: "outreach_sent",
    location: "Chicago, IL",
  },
  {
    name: "Kenji Sato",
    handle: "kenji.esports",
    bio: "League of Legends coach | Content creator | Tokyo gaming scene | Streetwear at LAN events",
    followers: 38000,
    engagement: 6.9,
    niche: ["gaming", "esports", "fashion"],
    tags: ["esports", "competitive"],
    verticals: ["gaming"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "qualified",
    location: "Tokyo, Japan",
  },
  // --- Micro (4) ---
  {
    name: "Bria Johnson",
    handle: "bria.gamergirl",
    bio: "Cozy gamer | Animal Crossing, Stardew Valley | Fashion hauls & gaming hauls | She/her",
    followers: 21000,
    engagement: 9.6,
    niche: ["gaming", "casual", "fashion"],
    tags: ["casual", "content-creator"],
    verticals: ["gaming", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "#gamingfashion",
    stage: "outreach_sent",
    location: "Portland, OR",
  },
  {
    name: "Oscar Rivera",
    handle: "oscar.pcbuild",
    bio: "PC builder & modder | RGB everything | Tech reviews + fit checks | Gaming setup tours",
    followers: 15800,
    engagement: 8.9,
    niche: ["gaming", "tech", "fashion"],
    tags: ["pc-gaming", "content-creator"],
    verticals: ["gaming"],
    source: "scraper_hashtag",
    discoveredFrom: "#gamingfashion",
    stage: "discovered",
    location: "Austin, TX",
  },
  {
    name: "Hannah Kim",
    handle: "hannahkim.vr",
    bio: "VR content creator | Beat Saber queen | Exploring virtual worlds in real fashion | Next-gen",
    followers: 12500,
    engagement: 10.7,
    niche: ["gaming", "vr", "tech"],
    tags: ["vr", "content-creator"],
    verticals: ["gaming"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Seoul, South Korea",
  },
  {
    name: "Devon Marshall",
    handle: "devon.fps",
    bio: "FPS grinder | Apex Legends main | Small streamer big dreams | Drip check before every stream",
    followers: 8400,
    engagement: 12.0,
    niche: ["gaming", "fps", "streaming"],
    tags: ["competitive", "streaming"],
    verticals: ["gaming"],
    source: "scraper_comment",
    discoveredFrom: "#gamingfashion",
    stage: "discovered",
    location: "Atlanta, GA",
  },
];

// ============================================================
//  ART PROFILES (12)
// ============================================================

export const ART_PROFILES: ProfileSeed[] = [
  // --- Mega (1) ---
  {
    name: "Alex Morel",
    handle: "lensbyalex",
    bio: "Photographer | Shot campaigns for Nike, Dior, Palm Angels | Editorial & street | Rep: @artpartners",
    followers: 1500000,
    engagement: 3.0,
    niche: ["art", "photography", "fashion"],
    tags: ["photography", "editorial", "streetwear"],
    verticals: ["art", "fashion"],
    source: "manual_add",
    discoveredFrom: "@playbypalmangels",
    stage: "active",
    fee: 15000,
    location: "New York, NY",
    flags: ["vip", "brand_safe"],
  },
  // --- Macro (3) ---
  {
    name: "Roy Nakamura",
    handle: "visualbyroy",
    bio: "Visual artist | Digital + physical | Exhibited at Art Basel, Frieze | Creating worlds through color",
    followers: 420000,
    engagement: 4.5,
    niche: ["art", "digital-art", "gallery"],
    tags: ["digital-art", "visual-art"],
    verticals: ["art"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Los Angeles, CA",
  },
  {
    name: "Maya Okonkwo",
    handle: "artof.maya",
    bio: "Mixed media artist | Exploring identity through paint & textile | Gallery shows worldwide | She/her",
    followers: 280000,
    engagement: 5.2,
    niche: ["art", "painting", "textile"],
    tags: ["painting", "visual-art"],
    verticals: ["art"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "responded",
    location: "Lagos, Nigeria",
  },
  {
    name: "Daniel Park",
    handle: "danielpark.film",
    bio: "Filmmaker & director | Music videos, short films, brand campaigns | Cinematic everything",
    followers: 195000,
    engagement: 4.8,
    niche: ["art", "film", "music-video"],
    tags: ["film", "music-video"],
    verticals: ["art", "music"],
    source: "referral",
    discoveredFrom: "@playbypalmangels",
    stage: "negotiating",
    location: "Seoul, South Korea",
  },
  // --- Mid (4) ---
  {
    name: "Sasha Ivanova",
    handle: "sasha.illustrates",
    bio: "Fashion illustrator | Drawing runway looks | Clients: Gucci, Prada, Palm Angels | Prints available",
    followers: 68000,
    engagement: 7.0,
    niche: ["art", "illustration", "fashion"],
    tags: ["illustration", "visual-art"],
    verticals: ["art", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "outreach_sent",
    location: "Moscow, Russia",
  },
  {
    name: "Jordan Reeves",
    handle: "jordan3dart",
    bio: "3D artist | Creating surreal digital worlds | NFT drops | Blender & Unreal Engine daily",
    followers: 52000,
    engagement: 6.8,
    niche: ["art", "3d", "digital"],
    tags: ["3d-art", "digital-art", "nft"],
    verticals: ["art"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "qualified",
    location: "London, UK",
  },
  {
    name: "Carmen Delgado",
    handle: "carmendelgado.lens",
    bio: "Street photographer | Documenting city culture | B&W film | Capturing the world in moments",
    followers: 41000,
    engagement: 8.3,
    niche: ["art", "photography", "street"],
    tags: ["photography", "visual-art"],
    verticals: ["art", "culture"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "outreach_sent",
    location: "Mexico City, MX",
  },
  {
    name: "Theo Baptiste",
    handle: "theobaptiste.art",
    bio: "Graffiti artist turned gallery | Murals worldwide | Collaborations with fashion brands | Paint is life",
    followers: 36000,
    engagement: 7.5,
    niche: ["art", "graffiti", "mural"],
    tags: ["painting", "visual-art"],
    verticals: ["art", "culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Paris, France",
  },
  // --- Micro (4) ---
  {
    name: "Iris Chen",
    handle: "iris.motiondesign",
    bio: "Motion designer | After Effects wizard | Creating visual magic for brands | Freelance open",
    followers: 19500,
    engagement: 9.4,
    niche: ["art", "animation", "design"],
    tags: ["animation", "graphic-design"],
    verticals: ["art"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Berlin, Germany",
  },
  {
    name: "Malik Jefferson",
    handle: "malik.darkroom",
    bio: "Film photographer | 35mm only | Developing in my bathroom | Analog aesthetic forever",
    followers: 14200,
    engagement: 10.8,
    niche: ["art", "photography", "film"],
    tags: ["photography", "film"],
    verticals: ["art"],
    source: "scraper_hashtag",
    discoveredFrom: "#palmangels",
    stage: "discovered",
    location: "Oakland, CA",
  },
  {
    name: "Yuna Park",
    handle: "yunapark.type",
    bio: "Typography & lettering artist | Custom fonts for brands | Turning words into art | Seoul based",
    followers: 11800,
    engagement: 9.0,
    niche: ["art", "typography", "design"],
    tags: ["graphic-design", "visual-art"],
    verticals: ["art"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Seoul, South Korea",
  },
  {
    name: "Emmett Walsh",
    handle: "emmett.collage",
    bio: "Collage artist | Cutting up magazines since 2015 | Fashion x art crossover | Prints & originals",
    followers: 7900,
    engagement: 13.2,
    niche: ["art", "collage", "fashion"],
    tags: ["visual-art", "illustration"],
    verticals: ["art", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "discovered",
    location: "Denver, CO",
  },
];

// ============================================================
//  CULTURE PROFILES (14)
// ============================================================

export const CULTURE_PROFILES: ProfileSeed[] = [
  // --- Mega (2) ---
  {
    name: "Nico Vargas",
    handle: "nightowl.nyc",
    bio: "NYC nightlife king | Club promoter | Documenting the scene | Fashion after midnight | DM for guestlist",
    followers: 1400000,
    engagement: 3.3,
    niche: ["culture", "nightlife", "fashion"],
    tags: ["nightlife", "entertainment", "streetwear"],
    verticals: ["culture", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "onboarded",
    fee: 10000,
    location: "New York, NY",
    flags: ["vip"],
  },
  {
    name: "Jasmine Tran",
    handle: "tastemkr",
    bio: "Tastemaker | Food, fashion, travel | 50 countries & counting | Curating the good life | Press inquiries: jt@mgmt.co",
    followers: 1650000,
    engagement: 2.7,
    niche: ["culture", "food", "travel"],
    tags: ["lifestyle", "travel", "foodie"],
    verticals: ["culture"],
    source: "agency_submit",
    discoveredFrom: "@playbypalmangels",
    stage: "negotiating",
    location: "Los Angeles, CA",
    flags: ["vip"],
  },
  // --- Macro (3) ---
  {
    name: "Andre Lewis",
    handle: "cityvibes.la",
    bio: "LA culture curator | Best restaurants, bars, events | Streetwear scene guide | Your LA plug",
    followers: 390000,
    engagement: 4.6,
    niche: ["culture", "lifestyle", "food"],
    tags: ["lifestyle", "foodie", "nightlife"],
    verticals: ["culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Los Angeles, CA",
  },
  {
    name: "Priya Mehta",
    handle: "priyaexplores",
    bio: "Travel photographer | Luxury travel meets street culture | Exploring every continent in Palm Angels",
    followers: 270000,
    engagement: 5.0,
    niche: ["culture", "travel", "photography"],
    tags: ["travel", "lifestyle"],
    verticals: ["culture", "art"],
    source: "scraper_comment",
    discoveredFrom: "@emmachamberlain",
    stage: "responded",
    location: "Dubai, UAE",
  },
  {
    name: "Felix Montague",
    handle: "felix.eats",
    bio: "Food critic & content creator | Michelin to street food | NYC dining guide | Fashion on the side",
    followers: 215000,
    engagement: 4.3,
    niche: ["culture", "food", "lifestyle"],
    tags: ["foodie", "lifestyle"],
    verticals: ["culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "New York, NY",
  },
  // --- Mid (5) ---
  {
    name: "Luna Kim",
    handle: "luna.seoulnights",
    bio: "Seoul nightlife & culture | K-fashion meets streetwear | Club reviews & city guides | Living nocturnally",
    followers: 74000,
    engagement: 6.4,
    niche: ["culture", "nightlife", "fashion"],
    tags: ["nightlife", "entertainment", "streetwear"],
    verticals: ["culture", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Seoul, South Korea",
  },
  {
    name: "Diego Costa",
    handle: "diego.viajero",
    bio: "Travel content creator | Backpacking with style | Latin America focus | Fashion-forward nomad life",
    followers: 58000,
    engagement: 7.0,
    niche: ["culture", "travel", "lifestyle"],
    tags: ["travel", "lifestyle"],
    verticals: ["culture"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "qualified",
    location: "Buenos Aires, Argentina",
  },
  {
    name: "Rachel Green",
    handle: "rachel.mixologist",
    bio: "Cocktail creator | Bar consultant | Mixing drinks & mixing fashion | The bar cart is my runway",
    followers: 42000,
    engagement: 6.8,
    niche: ["culture", "cocktails", "lifestyle"],
    tags: ["cocktails", "hospitality"],
    verticals: ["culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "London, UK",
  },
  {
    name: "Marcus Brown",
    handle: "marcusb.events",
    bio: "Event planner & curator | Fashion shows, art openings, launch parties | Making moments | NYC/LA",
    followers: 36000,
    engagement: 7.5,
    niche: ["culture", "events", "fashion"],
    tags: ["events", "entertainment"],
    verticals: ["culture", "fashion"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "New York, NY",
  },
  {
    name: "Hana Sato",
    handle: "hana.tokyobites",
    bio: "Tokyo food & culture blogger | Ramen to fine dining | Exploring Japan one bite at a time",
    followers: 48000,
    engagement: 8.1,
    niche: ["culture", "food", "travel"],
    tags: ["foodie", "travel"],
    verticals: ["culture"],
    source: "scraper_hashtag",
    discoveredFrom: "#palmangels",
    stage: "discovered",
    location: "Tokyo, Japan",
  },
  // --- Micro (4) ---
  {
    name: "Oliver Bennett",
    handle: "oliver.barscene",
    bio: "Bar hopper | Reviewing cocktail bars worldwide | Fashion & drinks content | Living my best life",
    followers: 22000,
    engagement: 8.8,
    niche: ["culture", "cocktails", "nightlife"],
    tags: ["cocktails", "nightlife"],
    verticals: ["culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Melbourne, Australia",
  },
  {
    name: "Aaliyah Thompson",
    handle: "aaliyah.citylights",
    bio: "Urban culture explorer | Street festivals, pop-ups, hidden gems | Fashion meets the city",
    followers: 15800,
    engagement: 9.2,
    niche: ["culture", "lifestyle", "urban"],
    tags: ["lifestyle", "entertainment"],
    verticals: ["culture"],
    source: "scraper_comment",
    discoveredFrom: "#streetwear",
    stage: "discovered",
    location: "Chicago, IL",
  },
  {
    name: "Pierre Dubois",
    handle: "pierre.sommelier",
    bio: "Wine & spirits content | Sommelier certified | Fashion and fine wine share one thing: taste",
    followers: 11500,
    engagement: 10.5,
    niche: ["culture", "wine", "lifestyle"],
    tags: ["wine", "lifestyle"],
    verticals: ["culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Bordeaux, France",
  },
  {
    name: "Keiko Yamada",
    handle: "keiko.kyotostyle",
    bio: "Kyoto culture guide | Traditional meets modern | Tea ceremonies in sneakers | Japan lifestyle",
    followers: 9200,
    engagement: 11.8,
    niche: ["culture", "travel", "lifestyle"],
    tags: ["travel", "lifestyle"],
    verticals: ["culture"],
    source: "referral",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Kyoto, Japan",
  },
];

// ============================================================
//  HEALTH PROFILES (10)
// ============================================================

export const HEALTH_PROFILES: ProfileSeed[] = [
  // --- Mega (1) ---
  {
    name: "Sara Mitchell",
    handle: "flexwithsara",
    bio: "Certified PT | 1M+ transformation stories | Athleisure queen | Nike Training, Palm Angels gym fits | Book a session",
    followers: 1300000,
    engagement: 3.6,
    niche: ["health", "fitness", "athleisure"],
    tags: ["fitness", "wellness", "athleisure"],
    verticals: ["health", "fashion"],
    source: "agency_submit",
    discoveredFrom: "@playbypalmangels",
    stage: "contracted",
    fee: 9000,
    location: "Los Angeles, CA",
    flags: ["brand_safe"],
  },
  // --- Macro (2) ---
  {
    name: "Kenzo Abe",
    handle: "zenmaster.k",
    bio: "Yoga instructor | Mindfulness teacher | 500hr RYT | Blending eastern philosophy with modern style | Breathe",
    followers: 260000,
    engagement: 5.4,
    niche: ["health", "yoga", "mindfulness"],
    tags: ["yoga", "mindfulness", "wellness"],
    verticals: ["health"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Bali, Indonesia",
  },
  {
    name: "Jordan Hayes",
    handle: "fitfuelco",
    bio: "Nutrition coach | Meal prep king | Macros & muscle | Helping you eat to perform | Athleisure lifestyle",
    followers: 185000,
    engagement: 4.9,
    niche: ["health", "nutrition", "fitness"],
    tags: ["nutrition", "fitness", "supplements"],
    verticals: ["health"],
    source: "scraper_comment",
    discoveredFrom: "#fitcheck",
    stage: "responded",
    location: "Miami, FL",
  },
  // --- Mid (4) ---
  {
    name: "Camille Dubois",
    handle: "camille.pilates",
    bio: "Pilates instructor | Reformer specialist | Mind-body connection | French wellness in NYC | Athleisure daily",
    followers: 72000,
    engagement: 6.7,
    niche: ["health", "pilates", "wellness"],
    tags: ["pilates", "wellness"],
    verticals: ["health"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "New York, NY",
  },
  {
    name: "Marcus Young",
    handle: "marcusy.crossfit",
    bio: "CrossFit athlete | Regional competitor | Training content daily | Functional fitness meets street style",
    followers: 54000,
    engagement: 7.3,
    niche: ["health", "crossfit", "fitness"],
    tags: ["crossfit", "fitness"],
    verticals: ["health", "sports"],
    source: "scraper_comment",
    discoveredFrom: "#fitcheck",
    stage: "qualified",
    location: "Denver, CO",
  },
  {
    name: "Lila Pham",
    handle: "lila.skinwell",
    bio: "Skincare scientist | Dermatology resident | Product reviews & routines | Wellness from the outside in",
    followers: 48000,
    engagement: 8.0,
    niche: ["health", "skincare", "wellness"],
    tags: ["skincare", "wellness"],
    verticals: ["health"],
    source: "scraper_comment",
    discoveredFrom: "@emmachamberlain",
    stage: "outreach_sent",
    location: "San Francisco, CA",
  },
  {
    name: "Darius Reed",
    handle: "darius.mindfit",
    bio: "Mental health advocate | Fitness & therapy | Breaking stigmas in the gym | Strong body, strong mind",
    followers: 31000,
    engagement: 8.6,
    niche: ["health", "mental-health", "fitness"],
    tags: ["mental-health", "fitness", "wellness"],
    verticals: ["health"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Philadelphia, PA",
  },
  // --- Micro (3) ---
  {
    name: "Emi Tanaka",
    handle: "emi.breathwork",
    bio: "Breathwork facilitator | Sound healing | Holistic wellness | Finding peace in the chaos | Tokyo & LA",
    followers: 16500,
    engagement: 9.8,
    niche: ["health", "mindfulness", "holistic"],
    tags: ["mindfulness", "meditation", "wellness"],
    verticals: ["health"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Tokyo, Japan",
  },
  {
    name: "Ryan Cooper",
    handle: "ryan.biohack",
    bio: "Biohacker | Cold plunge evangelist | Optimizing everything | Tracking sleep, HRV, and drip",
    followers: 12800,
    engagement: 10.2,
    niche: ["health", "biohacking", "fitness"],
    tags: ["supplements", "recovery", "wellness"],
    verticals: ["health"],
    source: "scraper_hashtag",
    discoveredFrom: "#fitcheck",
    stage: "discovered",
    location: "Austin, TX",
  },
  {
    name: "Zara Osman",
    handle: "zara.wellnessco",
    bio: "Wellness blogger | Vegan recipes | Meditation guides | Athleisure fashion content | She/her",
    followers: 8300,
    engagement: 12.5,
    niche: ["health", "wellness", "vegan"],
    tags: ["wellness", "nutrition"],
    verticals: ["health"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "discovered",
    location: "London, UK",
  },
];

// ============================================================
//  OUTDOORS PROFILES (8)
// ============================================================

export const OUTDOORS_PROFILES: ProfileSeed[] = [
  // --- Mega (1) ---
  {
    name: "Jesse Quinn",
    handle: "summitseeker",
    bio: "Mountaineer | 7 summits project | National Geographic contributor | Adventure fashion pioneer | The mountain is the runway",
    followers: 1900000,
    engagement: 3.4,
    niche: ["outdoors", "mountaineering", "adventure"],
    tags: ["mountaineering", "adventure", "streetwear"],
    verticals: ["outdoors"],
    source: "manual_add",
    discoveredFrom: "@playbypalmangels",
    stage: "negotiating",
    location: "Jackson Hole, WY",
    flags: ["vip"],
  },
  // --- Macro (2) ---
  {
    name: "Jess Morales",
    handle: "waveriderjess",
    bio: "Surfer & ocean advocate | Clean water activist | Roxy, Patagonia, Palm Angels | Salt life forever",
    followers: 340000,
    engagement: 4.7,
    niche: ["outdoors", "surfing", "environment"],
    tags: ["surfing", "adventure"],
    verticals: ["outdoors", "sports"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Byron Bay, Australia",
  },
  {
    name: "Ben Calloway",
    handle: "trailblaze.co",
    bio: "Trail runner & adventure photographer | 100-mile races | Documenting the wild | Arc'teryx, Salomon, PA",
    followers: 215000,
    engagement: 5.1,
    niche: ["outdoors", "trail-running", "photography"],
    tags: ["trail-running", "adventure"],
    verticals: ["outdoors", "art"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "responded",
    location: "Boulder, CO",
  },
  // --- Mid (3) ---
  {
    name: "Ana Torres",
    handle: "ana.vanlife",
    bio: "Full-time vanlifer | Exploring North America | Outdoor fashion content | Home is where I park it",
    followers: 68000,
    engagement: 7.2,
    niche: ["outdoors", "vanlife", "travel"],
    tags: ["vanlife", "adventure", "travel"],
    verticals: ["outdoors", "culture"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Moab, UT",
  },
  {
    name: "Liam O'Sullivan",
    handle: "liam.wildcamp",
    bio: "Wild camper & bushcrafter | Scottish Highlands based | Campfire cooking | Outdoor gear reviews",
    followers: 42000,
    engagement: 8.0,
    niche: ["outdoors", "camping", "bushcraft"],
    tags: ["camping", "adventure"],
    verticals: ["outdoors"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "qualified",
    location: "Edinburgh, Scotland",
  },
  {
    name: "Kira Johansson",
    handle: "kira.climbson",
    bio: "Rock climber | V8 boulderer | Climbing in style | Adventure meets fashion | Stockholm girl on the wall",
    followers: 35000,
    engagement: 8.5,
    niche: ["outdoors", "climbing", "adventure"],
    tags: ["climbing", "adventure"],
    verticals: ["outdoors", "sports"],
    source: "scraper_comment",
    discoveredFrom: "@playbypalmangels",
    stage: "outreach_sent",
    location: "Stockholm, Sweden",
  },
  // --- Micro (2) ---
  {
    name: "Tomas Reyes",
    handle: "tomas.kayaklife",
    bio: "Kayaker & outdoor filmmaker | Whitewater adventures | Documenting rivers worldwide | Paddle on",
    followers: 18500,
    engagement: 9.6,
    niche: ["outdoors", "kayaking", "film"],
    tags: ["adventure", "cycling"],
    verticals: ["outdoors"],
    source: "scraper_comment",
    discoveredFrom: "#palmangels",
    stage: "discovered",
    location: "Santiago, Chile",
  },
  {
    name: "Freya Nielsen",
    handle: "freya.nordictrails",
    bio: "Nordic hiker | Long-distance trails | Fjord to forest | Outdoor athleisure content | Norway calling",
    followers: 11200,
    engagement: 10.9,
    niche: ["outdoors", "hiking", "nordic"],
    tags: ["hiking", "adventure"],
    verticals: ["outdoors"],
    source: "referral",
    discoveredFrom: "@playbypalmangels",
    stage: "researching",
    location: "Oslo, Norway",
  },
];

// ============================================================
//  Combined exports
// ============================================================

export const ALL_PROFILES: ProfileSeed[] = [
  ...FASHION_PROFILES,
  ...MUSIC_PROFILES,
  ...SPORTS_PROFILES,
  ...GAMING_PROFILES,
  ...ART_PROFILES,
  ...CULTURE_PROFILES,
  ...HEALTH_PROFILES,
  ...OUTDOORS_PROFILES,
];

export function generateAllInfluencers(): InfluencerRecord[] {
  return ALL_PROFILES.map((seed, i) => makeInfluencer(seed, i));
}
